#!/bin/bash

clear
# 检查是否是 root 用户
if [ "$EUID" -ne 0 ]; then
    echo "错误：请使用 root 用户执行此脚本。"
    exit
fi

echo "Hello! 欢迎使用数码乱炖的的dd系统脚本"
echo "有问题请提 issue，GitHub 地址：https://github.com/bihell/debian-dd"
echo "VPS 服务器整理：https://bigdata.icu/tools/vps.html"
echo "油管：https://www.youtube.com/channel/UCINmrFonh6v0VTyWhudSQ2w"
echo "B站：https://space.bilibili.com/88900889"
echo "西瓜：https://space.bilibili.com/88900889"
echo
echo "支持的版本:"
echo "[1] Debian 12 <bookworm> 版本号 12.5"
echo "[2] Debian 11 <bullseye> 版本号 11.9"
echo "[3] Debian 10 <buster> 版本号 10.13"
read -p "请选择[默认1]：" version

if [ -z "$version" ]; then
    version=0
fi

if [ "$version" == "0" ] || [ "$version" == "1" ]; then
    debian_version="Debian12.5"
elif [ "$version" == "2" ]; then
    debian_version="Debian11.9"
elif [ "$version" == "3" ]; then
    debian_version="Debian10.13"
else 
    echo "未输入正确的选项,准备退出..."
    sleep 1
    exit
fi
	
echo "即将安装$debian_version..."
echo
echo "设置root密码[默认digital-review]:"
read -p "建议强密码[直接回车则是默认密码]" passwd
if [ -z "$passwd" ]; then
	passwd="digital-review"
	echo "重装好之后请立刻登陆修改root密码！！！"
	sleep 1
fi

# 获取根目录的设备号
root_device=$(df / | awk 'NR==2 {print $1}')
# 从设备号中提取分区号
partitionr_root_number=$(echo "$root_device" | grep -oE '[0-9]+$')

mkdir /netboot && cd /netboot
apt install wget -y
wget https://ftp.debian.org/debian/dists/$debian_version/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux
wget https://ftp.debian.org/debian/dists/$debian_version/main/installer-amd64/current/images/netboot/debian-installer/amd64/initrd.gz

apt install net-tools -y
# 获取活动网络接口名称
interface=$(ip -o link show | awk '$2 != "lo:" {print substr($2, 1, length($2)-1); exit}')

# 获取IP地址
ip=$(ifconfig $interface | awk '/inet / {print $2}')

# 获取子网掩码
netmask=$(ifconfig $interface | awk '/netmask / {print $4}')

# 获取网关
gateway=$(ip route | awk '/default/ {print $3}')

echo "开始配置preseed.cfg..."
mkdir temp_initrd
cd temp_initrd
gunzip -c ../initrd.gz | cpio -i

cat << EOF > preseed.cfg
d-i debian-installer/locale string en_US.UTF-8
d-i debian-installer/language string en
d-i debian-installer/country string CN
d-i keyboard-configuration/xkb-keymap select us
d-i passwd/make-user boolean false
d-i passwd/root-password password $passwd
d-i passwd/root-password-again password $passwd
d-i user-setup/allow-password-weak boolean true
d-i netcfg/choose_interface select auto
d-i netcfg/dhcp_failed note
d-i netcfg/dhcp_options select Configure network manually
d-i netcfg/get_ipaddress string $ip
d-i netcfg/get_netmask string $netmask
d-i netcfg/get_gateway string $gateway
d-i netcfg/get_nameservers string 1.1.1.1 8.8.8.8
d-i netcfg/confirm_static boolean true
d-i netcfg/get_hostname string debian
d-i netcfg/get_domain string debian

### Mirror settings
d-i mirror/country string manual
d-i mirror/http/hostname string deb.debian.org
d-i mirror/http/directory string /debian
d-i mirror/http/proxy string

d-i clock-setup/utc boolean true
d-i clock-setup/ntp boolean true
d-i time/zone string Asia/Shanghai
d-i partman-auto/disk string /dev/[sv]da
d-i partman-auto/method string regular
d-i partman-lvm/device_remove_lvm boolean true
d-i partman-md/device_remove_md boolean true
d-i partman-basicfilesystems/no_swap boolean false
d-i partman-auto/expert_recipe string                       \
200 1 200 ext4 \
        \$primary{ } \$bootable{ } \
        method{ format } format{ } \
        use_filesystem{ } filesystem{ ext4 } \
        mountpoint{ /boot } \
    . \
201 2 -1 ext4 \
        \$primary{ } \
        method{ format } format{ } \
        use_filesystem{ } filesystem{ ext4 } \
        mountpoint{ / } \
    .
d-i partman-md/confirm_nooverwrite boolean true
d-i partman-lvm/confirm_nooverwrite boolean true
d-i partman/confirm_write_new_label boolean true
d-i partman/choose_partition select finish
d-i partman/confirm boolean true
tasksel tasksel/first multiselect minimal
d-i pkgsel/include string openssh-server
d-i pkgsel/update-policy select none
d-i pkgsel/upgrade select none
d-i apt-setup/services-select multiselect
d-i grub-installer/grub2_instead_of_grub_legacy boolean true
d-i grub-installer/only_debian boolean true
d-i grub-installer/bootdev string /dev/[sv]da
d-i preseed/late_command string \
chroot /target sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config;
d-i finish-install/reboot_in_progress note
EOF
find . | cpio -H newc -o | gzip -6 > ../initrd.gz && cd ..
rm -rf temp_initrd 
echo "配置完成，即将开始重装..."
cat << EOF >> /etc/grub.d/40_custom
menuentry "Digital-Review Debian Installer AMD64" {
    set root="(hd0,$partitionr_root_number)"
    linux /netboot/linux auto=true priority=critical lowmem/low=true preseed/file=/preseed.cfg
    initrd /netboot/initrd.gz
}
EOF

# 修改GRUB_DEFAULT选项
sed -i 's/^GRUB_DEFAULT=.*/GRUB_DEFAULT=2/' /etc/default/grub
# 修改GRUB_TIMEOUT选项
sed -i 's/^GRUB_TIMEOUT=.*/GRUB_TIMEOUT=2/' /etc/default/grub

update-grub && reboot
